FROM ubuntu:18.04
Run apt-get update
Run apt-get install -y openvswitch-switch openvswitch-common logrotate
COPY docker/launch-ovs.sh docker/liveness-ovs.sh dist-static/ovsresync /usr/local/bin/
CMD ["/usr/local/bin/launch-ovs.sh"]
