FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
RUN microdnf update && microdnf install libstdc++ libuv \
  boost-program-options boost-system boost-date-time boost-filesystem \
  boost-iostreams libnetfilter_conntrack openssl
COPY bin/* /usr/local/bin/
COPY lib/* /usr/local/lib/
ENV SSL_MODE="encrypted"
ENV REBOOT_WITH_OVS="true"
CMD ["/usr/local/bin/launch-opflexagent.sh"]
